import type { Question, SurveyScoreConfig } from "@shared/schema";
import { normalizeQuestions } from "./questionNormalization";

export interface SurveyTemplate {
  id: string;
  title: string;
  description: string;
  timing: string;
  audience: string;
  topic: "assessment" | "feedback" | "knowledge" | "satisfaction" | "application" | "manager" | "roi";
  questionCount: number;
  questions: Question[];
  welcomeMessage?: string;
  thankYouMessage?: string;
  resultsSummary?: string;
  scoreConfig?: SurveyScoreConfig;
  // Optional metadata used for sorting/filtering in the template library and persistence layers
  category?: string;
  subCategory?: string;
  templateType?: string;
  targetAudience?: string;
  estimatedMinutes?: number;
  tags?: string[];
}

// Base templates (raw content). Scoring will be applied to assessment templates below.
const baseTemplates: SurveyTemplate[] = [
  {
    id: "pre_training_needs_assessment",
    title: "Pre-Training Needs Assessment",
    description: "Identifies current skill level, pain points, and expectations before training.",
    timing: "Before training",
    audience: "Participants",
    topic: "assessment",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "dropdown",
        question: "Which best describes your current role?",
        options: ["Individual contributor", "People manager", "Senior leader / executive", "Other"],
        placeholder: "Select your role...",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How familiar are you with the topic of this training?",
        ratingScale: 5,
        ratingStyle: "number",
        ratingLabels: { low: "Not familiar", high: "Very familiar" },
        required: true,
      },
      {
        id: "q3",
        type: "slider",
        question: "How confident do you currently feel performing tasks related to this topic?",
        min: 0,
        max: 100,
        step: 10,
        unit: "%",
        showValue: true,
        required: true,
      },
      {
        id: "q4",
        type: "checkbox",
        question: "Which areas do you struggle with most related to this topic?",
        options: ["I don't know what to do", "I know what to do but find it hard to do", "Time pressure / workload", "Tools, systems, or processes", "Lack of support or alignment from others", "Other"],
        displayStyle: "cards",
        allowOther: true,
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What would make this training most valuable for you personally?",
        placeholder: "Share your thoughts...",
        rows: 4,
        required: false,
      },
      {
        id: "q6",
        type: "likert",
        question: "How urgent is it for you to improve your skills in this area?",
        likertType: "importance",
        likertPoints: 5,
        required: true,
      },
      {
        id: "q7",
        type: "rating",
        question: "How clear are you on what success in this area looks like in your role?",
        ratingScale: 5,
        ratingStyle: "star",
        ratingLabels: { low: "Not clear", high: "Very clear" },
        required: false,
      },
      {
        id: "q8",
        type: "multiple_choice",
        question: "Which best describes your current overall workload during the period of this training?",
        options: ["Lighter than usual", "About normal", "Heavier than usual", "Extremely heavy"],
        displayStyle: "cards",
        required: false,
      },
      {
        id: "q9",
        type: "yes_no",
        question: "Have you previously attended training on this or a closely related topic?",
        displayStyle: "buttons",
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "If you have any specific scenarios or cases you would like the training to address, please briefly describe them.",
        placeholder: "Describe specific scenarios...",
        rows: 5,
        required: false,
      },
    ],
  },
  {
    id: "pre_training_readiness_motivation",
    title: "Pre-Training Readiness & Motivation",
    description: "Assesses learner motivation, mindset, and potential barriers before training starts.",
    timing: "Before training",
    audience: "Participants",
    topic: "assessment",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "How motivated are you to actively participate in this training?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How relevant do you believe this training is to your current role and responsibilities?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "How much support do you feel you have from your manager to apply what you learn in this training?",
        required: true,
      },
      {
        id: "q4",
        type: "checkbox",
        question: "What might prevent you from fully engaging with this training?",
        options: ["Competing priorities / time conflicts", "Unclear relevance to my role", "Technology or access issues", "High workload during the training period", "Personal factors (energy, focus, etc.)", "Other"],
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "In one sentence, what would 'success' from this training look like for you?",
        required: false,
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "Do you understand the objectives and structure of this training?",
        options: ["Yes, very clear", "Somewhat clear", "Not clear at all"],
        required: true,
      },
      {
        id: "q7",
        type: "rating",
        question: "How comfortable are you with the format of this training (e.g., virtual, in-person, blended)?",
        required: false,
      },
      {
        id: "q8",
        type: "rating",
        question: "How confident are you in your ability to keep up with any pre-work or assignments associated with this training?",
        required: false,
      },
      {
        id: "q9",
        type: "textarea",
        question: "Are there accessibility or learning needs we should be aware of to support your participation?",
        required: false,
      },
      {
        id: "q10",
        type: "rating",
        question: "How important is this training for your career development in the next 12 months?",
        required: false,
      },
    ],
  },
  {
    id: "mid_training_pulse_check",
    title: "Mid-Training Pulse Check",
    description: "Brief check-in during training to adjust pacing, format, and support.",
    timing: "During training",
    audience: "Participants",
    topic: "feedback",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "opinion_scale",
        question: "How would you rate the pace of the training so far?",
        ratingScale: 5,
        leftLabel: "Too slow",
        rightLabel: "Too fast",
        showNumbers: false,
        required: true,
      },
      {
        id: "q2",
        type: "slider",
        question: "How confident do you feel in your understanding of the material covered so far?",
        min: 0,
        max: 100,
        step: 5,
        unit: "%",
        showValue: true,
        required: true,
      },
      {
        id: "q3",
        type: "constant_sum",
        question: "Distribute 100 points across these training components based on how helpful they are for your learning:",
        options: ["Presentations / lectures", "Group discussions", "Hands-on activities", "Case studies", "Reference materials"],
        totalPoints: 100,
        showPercentage: true,
        required: false,
      },
      {
        id: "q4",
        type: "rating",
        question: "How engaged do you feel during the sessions so far?",
        ratingScale: 5,
        ratingStyle: "emoji",
        ratingLabels: { low: "Disengaged", high: "Fully engaged" },
        required: true,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What is one thing the trainer could change right now to improve your learning experience?",
        placeholder: "Share your immediate feedback...",
        rows: 3,
        required: false,
      },
      {
        id: "q6",
        type: "likert",
        question: "I feel comfortable asking questions or speaking up during the training.",
        likertType: "agreement",
        likertPoints: 5,
        required: true,
      },
      {
        id: "q7",
        type: "rating",
        question: "How satisfied are you with the opportunities to practice or apply the concepts?",
        ratingScale: 5,
        ratingStyle: "number",
        ratingLabels: { low: "Not satisfied", high: "Very satisfied" },
        required: false,
      },
      {
        id: "q8",
        type: "opinion_scale",
        question: "How well do the examples and scenarios reflect your real work situation?",
        ratingScale: 7,
        leftLabel: "Not realistic",
        rightLabel: "Very realistic",
        showNumbers: true,
        required: false,
      },
      {
        id: "q9",
        type: "text",
        question: "Is there any topic covered so far that needs to be revisited or clarified?",
        placeholder: "Name the topic...",
        required: false,
      },
      {
        id: "q10",
        type: "checkbox",
        question: "What improvements would help the remaining sessions?",
        options: ["More interactive exercises", "Better pacing", "More Q&A time", "Clearer explanations", "More real-world examples", "Better materials"],
        displayStyle: "cards",
        allowOther: true,
        required: false,
      },
    ],
  },
  {
    id: "leadership_style_canada_public_service_standard_v1",
    title: "Leadership Style – Canada Public Service (Standard)",
    description: "A self-assessment for managers and aspiring leaders in the Canadian public service, focusing on how you lead in a hybrid, unionized and equity-focused environment.",
    timing: "Anytime",
    audience: "Supervisors, team leads, managers and EX-equivalents in Canadian public sector organizations.",
    topic: "manager",
    questionCount: 20,
    resultsSummary: "Leadership style profile for Canadian public service leaders.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "I communicate a clear and compelling vision that connects our work to serving Canadians.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transformational",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "I model the values of integrity, inclusion and respect that I expect from others.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transformational",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "I invite my team to challenge assumptions and propose new ways to deliver better outcomes for Canadians.",
        description: "Innovation and continuous improvement in a highly regulated environment.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transformational",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "I help my team see how their work contributes to reconciliation, equity and public trust.",
        description: "Includes Truth and Reconciliation, equity for Black and other racialized public servants, and accessibility.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transformational",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q5",
        type: "multiple_choice",
        question: "In times of uncertainty (e.g., job cuts, reorganizations, policy shifts), I am transparent about what I know and what I do not know.",
        description: "Addresses frustration with vague corporate messages and lack of candour during change.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transformational",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "I set clear expectations, priorities and boundaries for my team, even when senior direction is ambiguous.",
        description: "Clarifying priorities in a complex policy and political environment.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transactional",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q7",
        type: "multiple_choice",
        question: "I follow through consistently on performance discussions, both positive and corrective.",
        description: "Avoiding 'nice but absent' leadership on performance issues.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transactional",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q8",
        type: "multiple_choice",
        question: "I use data, service standards and measurable outcomes to manage work, not just narratives about transformation.",
        description: "Responds to criticism of 'storytelling' executives who don't deliver.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transactional",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q9",
        type: "multiple_choice",
        question: "I make decisions in a timely way, even when consensus is hard to achieve.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transactional",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q10",
        type: "multiple_choice",
        question: "I clarify what is within our control and what is constrained by legislation, policy or collective agreements.",
        description: "Managing expectations in a highly regulated, unionized context.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "transactional",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q11",
        type: "multiple_choice",
        question: "I regularly check in on my team’s workload and stress levels and adjust where I can.",
        description: "Responds to high burnout and mental health concerns in the public service.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q12",
        type: "multiple_choice",
        question: "I give developmental feedback that is specific, actionable and tied to future opportunities.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q13",
        type: "multiple_choice",
        question: "I actively support career development for underrepresented groups on my team (e.g., Indigenous, Black and other racialized employees, persons with disabilities).",
        description: "Aligns with federal commitments to equity, diversity and inclusion.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q14",
        type: "multiple_choice",
        question: "I adapt my leadership approach to the needs, lived experience and strengths of each team member.",
        description: "Modern, inclusive leadership vs one-size-fits-all.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q15",
        type: "multiple_choice",
        question: "I create space for honest conversations about psychological safety, discrimination and workplace culture.",
        description: "Aligns with federal mental health and inclusion commitments.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q16",
        type: "multiple_choice",
        question: "I provide clear outcomes and then give my team autonomy in how they meet them.",
        description: "Balancing direction and autonomy in hybrid work.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "delegative",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q17",
        type: "multiple_choice",
        question: "I am clear and predictable about hybrid work expectations while still allowing reasonable flexibility.",
        description: "Responds to tension around return-to-office and hybrid models.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "delegative",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q18",
        type: "multiple_choice",
        question: "When conflict emerges on the team, I address it in a timely way rather than hoping it resolves itself.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "delegative",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q19",
        type: "multiple_choice",
        question: "I stay connected enough to the work that I can remove obstacles and champion my team when needed.",
        description: "Addresses complaints about executives rotating without deep file knowledge.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "delegative",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
      {
        id: "q20",
        type: "multiple_choice",
        question: "I am deliberate about which decisions I delegate and which I retain, so my team feels both trusted and supported.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "delegative",
        optionScores: {
          "Strongly disagree": 1,
          Disagree: 2,
          Neutral: 3,
          Agree: 4,
          "Strongly agree": 5,
        },
      },
    ],
    scoreConfig: {
      enabled: true,
      categories: [
        { id: "transformational", name: "Transformational / Visionary" },
        { id: "transactional", name: "Operational / Structured" },
        { id: "coaching", name: "Coaching / Developmental" },
        { id: "delegative", name: "Empowering / Delegative" },
      ],
      scoreRanges: [
        {
          id: "low",
          min: 0,
          max: 49,
          label: "Developing",
          headline: "You’re building your leadership foundations.",
          summary: "Your scores suggest that your leadership style is still forming. This is a good time to clarify your values, focus on one or two strengths and seek targeted development opportunities.",
          tone: "risk",
        },
        {
          id: "mid",
          min: 50,
          max: 74,
          label: "Emerging",
          headline: "You show many effective leadership behaviours.",
          summary: "You are doing many things well, and your team likely experiences you as generally supportive and competent. There are still a few gaps where greater consistency would strengthen trust and impact.",
          tone: "neutral",
        },
        {
          id: "high",
          min: 75,
          max: 100,
          label: "Strong",
          headline: "You demonstrate strong, modern leadership for the public service.",
          summary: "Your self-assessment suggests you are applying many of the behaviours expected of leaders in the Canadian public service: inclusive, evidence-informed and focused on both people and results.",
          tone: "strength",
        },
      ],
      resultsScreen: {
        enabled: true,
        layout: "bands",
        showTotalScore: true,
        showPercentage: true,
        showOverallBand: true,
        showCategoryBreakdown: true,
        showCategoryBands: true,
        showStrengthsAndRisks: true,
        showCallToAction: true,
        title: "Your Leadership Style Profile",
        subtitle: "How your leadership shows up for your team in today’s Canadian public service.",
        footerNote: "This is a self-assessment, not a performance rating. Use it as a starting point for reflection and development conversations.",
        ctaLabel: "Download your reflection guide",
        ctaUrl: "https://example.gov/internal/leadership-reflection",
        themeVariant: "teal",
        scoreRanges: [
          {
            id: "low",
            min: 0,
            max: 49,
            label: "Developing",
            headline: "You’re building your leadership foundations.",
            summary: "Focus on clarifying expectations, being visible for your team and building trust through consistent follow-through.",
            tone: "risk",
          },
          {
            id: "mid",
            min: 50,
            max: 74,
            label: "Emerging",
            headline: "You’re on your way as a modern public sector leader.",
            summary: "Leverage your strengths and choose one or two areas—such as psychological safety, inclusion or operational clarity—to focus your growth.",
            tone: "neutral",
          },
          {
            id: "high",
            min: 75,
            max: 100,
            label: "Strong",
            headline: "You’re modelling many of the behaviours Canada needs from its leaders.",
            summary: "Keep investing in your growth and consider mentoring emerging leaders, particularly from equity-deserving groups.",
            tone: "strength",
          },
        ],
        categories: [
          {
            categoryId: "transformational",
            show: true,
            bandsMode: "inherit",
            bandNarratives: [
              {
                bandId: "low",
                headline: "Clarify and live your leadership story.",
                summary: "Your scores suggest your team may not consistently feel a clear sense of purpose, values or direction. Start by articulating why your work matters and how it connects to Canadians, reconciliation and equity.",
              },
              {
                bandId: "mid",
                headline: "Your vision is emerging.",
                summary: "You communicate purpose and values in many situations. Look for ways to connect everyday tasks back to the bigger picture—including equity, climate and public trust.",
              },
              {
                bandId: "high",
                headline: "You lead with purpose and integrity.",
                summary: "You are likely seen as credible, values-based and future-focused. Protect time for reflection, learning and listening so you don’t burn out or lose touch with frontline realities.",
              },
            ],
          },
          {
            categoryId: "transactional",
            show: true,
            bandsMode: "inherit",
            bandNarratives: [
              {
                bandId: "low",
                headline: "Add more structure and follow-through.",
                summary: "Where expectations and performance conversations are fuzzy, people experience more stress and unfairness. Start with clear priorities, decision rights and timely feedback.",
              },
              {
                bandId: "mid",
                headline: "You balance structure and flexibility.",
                summary: "You are generally clear and consistent. Look for opportunities to simplify processes, reduce bureaucracy and protect your team from unnecessary churn.",
              },
              {
                bandId: "high",
                headline: "You provide clarity and accountability.",
                summary: "You likely excel at execution and delivery. Ensure you don’t become overly transactional—pair your strength in structure with coaching and inclusion.",
              },
            ],
          },
          {
            categoryId: "coaching",
            show: true,
            bandsMode: "inherit",
            bandNarratives: [
              {
                bandId: "low",
                headline: "Invest more in people and psychological safety.",
                summary: "With high levels of burnout and stress in the public service, your team needs you to be present, supportive and curious—not just productive.",
              },
              {
                bandId: "mid",
                headline: "You support growth, some of the time.",
                summary: "You are having some good development and inclusion conversations. Look for patterns: who gets feedback, stretch assignments and sponsorship—and who doesn’t?",
              },
              {
                bandId: "high",
                headline: "You are a growth and inclusion-focused leader.",
                summary: "You likely create space for honest dialogue about workload, mental health and inclusion. Guard your own wellbeing and keep building peer support with other leaders.",
              },
            ],
          },
          {
            categoryId: "delegative",
            show: true,
            bandsMode: "inherit",
            bandNarratives: [
              {
                bandId: "low",
                headline: "Your team may feel micromanaged or disempowered.",
                summary: "In a hybrid environment, people need autonomy and trust. Experiment with delegating more decisions while still providing clear guardrails.",
              },
              {
                bandId: "mid",
                headline: "You mix autonomy with oversight.",
                summary: "You’re finding a balance between control and trust. Clarify when you expect to be consulted and when the team can decide independently.",
              },
              {
                bandId: "high",
                headline: "You empower your team and respect their expertise.",
                summary: "You likely foster ownership and innovation. Make sure you stay close enough to understand risk, support your team and advocate for them with senior leadership.",
              },
            ],
          },
        ],
      },
    },
  },
  {
    id: "leadership_impact_canada_public_service_extended_v1",
    title: "Leadership Impact & Climate – Canada Public Service (Extended)",
    description: "A deeper leadership self-assessment for public sector leaders, exploring six dimensions: vision, execution, coaching, empowerment, equity & trust, and wellbeing & psychological safety.",
    timing: "Anytime",
    audience: "Managers, executives and senior advisors in Canadian federal, provincial and municipal public service.",
    topic: "manager",
    questionCount: 36,
    resultsSummary: "Leadership impact profile across six dimensions.",
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "I clearly communicate how our work contributes to outcomes that matter to Canadians, not just internal processes.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q2",
        type: "multiple_choice",
        question: "I help my team understand how our work relates to reconciliation with Indigenous Peoples and other commitments to equity and inclusion.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q3",
        type: "multiple_choice",
        question: "I am comfortable naming trade-offs openly (e.g., between cost, service quality, risk and equity impacts).",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "I translate strategic priorities into clear deliverables, timelines and decision points for my team.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "execution",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q5",
        type: "multiple_choice",
        question: "I ensure we measure progress with meaningful indicators, not just activity counts or optimistic narratives.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "execution",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "When initiatives stall, I address the blockers directly instead of rebranding the work as 'ongoing transformation'.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "execution",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q7",
        type: "multiple_choice",
        question: "I provide timely feedback that helps people understand what to sustain, start and stop.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q8",
        type: "multiple_choice",
        question: "I notice who gets stretch assignments, visibility and sponsorship—and intentionally correct any inequities.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q9",
        type: "multiple_choice",
        question: "I encourage colleagues to pursue leadership development, including people who may not see themselves represented in current leadership.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q10",
        type: "multiple_choice",
        question: "I give my team clear decision rights and guardrails, then allow them to decide how to get the work done.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "empowerment",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q11",
        type: "multiple_choice",
        question: "I trust people to manage their time and location (within policy) instead of equating presence with performance.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "empowerment",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q12",
        type: "multiple_choice",
        question: "I intervene quickly when autonomy becomes avoidance, confusion or unfair workload distribution.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "empowerment",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q13",
        type: "multiple_choice",
        question: "People feel safe raising concerns about discrimination, racism, harassment or bias with me.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q14",
        type: "multiple_choice",
        question: "I seek out perspectives from employees who are often marginalized or overlooked in decision-making.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q15",
        type: "multiple_choice",
        question: "I follow through on commitments related to equity, anti-racism and accessibility, not just talk about them.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q16",
        type: "multiple_choice",
        question: "When I make mistakes that affect trust, I acknowledge them and take concrete steps to repair.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q17",
        type: "multiple_choice",
        question: "I proactively watch for signs of burnout and emotional exhaustion on my team.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q18",
        type: "multiple_choice",
        question: "I am willing to push back on unrealistic demands or timelines that risk harming my team’s wellbeing.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q19",
        type: "multiple_choice",
        question: "I normalize using mental health supports and flexible work arrangements where appropriate.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q20",
        type: "multiple_choice",
        question: "I address toxic behaviours (e.g., blame, disrespect, exclusion) even when they come from high-status individuals.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q21",
        type: "multiple_choice",
        question: "I remain curious and open when frontline staff challenge leadership decisions.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q22",
        type: "multiple_choice",
        question: "I am transparent about the constraints I face from central agencies, ministers or legislation.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q23",
        type: "multiple_choice",
        question: "I am consistent between what I say about values and what I reward or tolerate in practice.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q24",
        type: "multiple_choice",
        question: "I actively develop successors and emerging leaders rather than concentrating opportunities among a few familiar names.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q25",
        type: "multiple_choice",
        question: "I make time to understand the operational realities of my team’s work instead of leading only through meetings and slide decks.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "execution",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q26",
        type: "multiple_choice",
        question: "I adjust how decisions are made (e.g., more collaborative vs directive) based on risk, urgency and impact on people.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "empowerment",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q27",
        type: "multiple_choice",
        question: "I encourage my team to flag ethical concerns, including those related to AI, data and algorithmic decisions impacting Canadians.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q28",
        type: "multiple_choice",
        question: "I use hybrid work in a way that is fair and transparent, not as a reward or punishment.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q29",
        type: "multiple_choice",
        question: "I regularly reflect on how my own identity, privilege and lived experience impact my leadership decisions.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "equity_trust",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q30",
        type: "multiple_choice",
        question: "I am willing to ask for feedback about my leadership and act on it, even when it is uncomfortable.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "coaching",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q31",
        type: "multiple_choice",
        question: "When pressure increases (e.g., media attention, ministerial interest), I protect my team from unnecessary chaos where possible.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q32",
        type: "multiple_choice",
        question: "I make deliberate choices about what to stop doing, not just add new priorities on top of existing work.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "execution",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q33",
        type: "multiple_choice",
        question: "My team understands how decisions are made and who is accountable for what.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "execution",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q34",
        type: "multiple_choice",
        question: "I balance short-term deliverables with long-term capacity building in my leadership decisions.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q35",
        type: "multiple_choice",
        question: "I am intentional about creating a sense of belonging for employees who work mostly remotely.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "wellbeing_safety",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
      {
        id: "q36",
        type: "multiple_choice",
        question: "I can explain how our team’s work supports sustainable development goals such as climate action, equity or public safety.",
        required: true,
        options: ["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"],
        scorable: true,
        scoringCategory: "vision",
        optionScores: { "Strongly disagree": 1, Disagree: 2, Neutral: 3, Agree: 4, "Strongly agree": 5 },
      },
    ],
    scoreConfig: {
      enabled: true,
      categories: [
        { id: "vision", name: "Vision & Strategic Clarity" },
        { id: "execution", name: "Execution & Delivery" },
        { id: "coaching", name: "Coaching & Development" },
        { id: "empowerment", name: "Empowerment & Decision Rights" },
        { id: "equity_trust", name: "Equity, Ethics & Trust" },
        { id: "wellbeing_safety", name: "Wellbeing & Psychological Safety" },
      ],
      scoreRanges: [
        { id: "low", min: 0, max: 49, label: "At Risk" },
        { id: "mid", min: 50, max: 74, label: "Developing" },
        { id: "high", min: 75, max: 100, label: "Strong" },
      ],
      resultsScreen: {
        enabled: true,
        layout: "dashboard",
        showTotalScore: true,
        showPercentage: true,
        showOverallBand: true,
        showCategoryBreakdown: true,
        showCategoryBands: true,
        showStrengthsAndRisks: true,
        showCallToAction: true,
        title: "Your Leadership Impact Profile",
        subtitle: "A multi-dimensional look at how you lead in the Canadian public service.",
        themeVariant: "neutral",
        scoreRanges: [
          { id: "low", min: 0, max: 49, label: "At Risk" },
          { id: "mid", min: 50, max: 74, label: "Developing" },
          { id: "high", min: 75, max: 100, label: "Strong" },
        ],
        categories: [
          { categoryId: "vision", show: true, bandsMode: "inherit" },
          { categoryId: "execution", show: true, bandsMode: "inherit" },
          { categoryId: "coaching", show: true, bandsMode: "inherit" },
          { categoryId: "empowerment", show: true, bandsMode: "inherit" },
          { categoryId: "equity_trust", show: true, bandsMode: "inherit" },
          { categoryId: "wellbeing_safety", show: true, bandsMode: "inherit" },
        ],
      },
    },
  },
  {
    id: "session_level_feedback",
    title: "Session-Level Feedback",
    description: "Captures feedback on a specific training session, module, or class.",
    timing: "Immediately after session",
    audience: "Participants",
    topic: "feedback",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "Overall, how would you rate this session?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "The objectives of the session were clear.",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "The trainer was well-prepared and organized.",
        required: true,
      },
      {
        id: "q4",
        type: "rating",
        question: "The content level (difficulty, depth) was appropriate for me.",
        required: true,
      },
      {
        id: "q5",
        type: "rating",
        question: "The session was engaging and kept my attention.",
        required: false,
      },
      {
        id: "q6",
        type: "rating",
        question: "The learning activities (discussions, exercises, polls, etc.) supported my understanding.",
        required: false,
      },
      {
        id: "q7",
        type: "textarea",
        question: "Which part(s) of this session did you find most valuable?",
        required: false,
      },
      {
        id: "q8",
        type: "textarea",
        question: "What, if anything, should be changed or improved in this session?",
        required: false,
      },
      {
        id: "q9",
        type: "multiple_choice",
        question: "Was the session length appropriate for the amount of content covered?",
        options: ["Much too short", "Somewhat too short", "Just right", "Somewhat too long", "Much too long"],
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "Do you have any additional comments for the trainer or organizers about this specific session?",
        required: false,
      },
    ],
  },
  {
    id: "post_training_knowledge_check",
    title: "Post-Training Knowledge Check",
    description: "Assesses knowledge and understanding immediately after training.",
    timing: "Immediately after training",
    audience: "Participants",
    topic: "knowledge",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "How confident are you that you can explain the key concepts covered in this training to a colleague?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How well do you understand when and where to apply what you learned?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "If you were given a real work scenario related to this topic, how confident are you that you could handle it using what you learned?",
        required: true,
      },
      {
        id: "q4",
        type: "textarea",
        question: "List one specific concept, tool, or technique from this training that you feel you understand very well.",
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "List one concept, tool, or technique that you would like more practice or clarification on.",
        required: false,
      },
      {
        id: "q6",
        type: "rating",
        question: "How likely are you to use what you learned in the next 2 weeks?",
        required: true,
      },
      {
        id: "q7",
        type: "multiple_choice",
        question: "Did this training fill specific knowledge gaps you had in this topic?",
        options: ["Yes, completely", "Yes, partially", "Not really", "I didn't have gaps"],
        required: false,
      },
      {
        id: "q8",
        type: "rating",
        question: "How well did the assessments, quizzes, or practice activities reflect the key learning objectives?",
        required: false,
      },
      {
        id: "q9",
        type: "textarea",
        question: "What is one real situation at work where you plan to use what you learned?",
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "What additional resources (job aids, guides, checklists) would help you retain and apply this knowledge?",
        required: false,
      },
    ],
  },
  {
    id: "post_training_satisfaction_experience",
    title: "Post-Training Satisfaction & Experience",
    description: "Measures reactions to the overall training experience (Level 1: Reaction).",
    timing: "Immediately after training",
    audience: "Participants",
    topic: "satisfaction",
    questionCount: 11,
    questions: [
      {
        id: "q1",
        type: "nps",
        question: "How likely are you to recommend this training to a colleague?",
        required: true,
      },
      {
        id: "q2",
        type: "likert",
        question: "The training met my expectations.",
        likertType: "agreement",
        likertPoints: 5,
        required: true,
      },
      {
        id: "q3",
        type: "likert",
        question: "The trainer created an inclusive and respectful learning environment.",
        likertType: "agreement",
        likertPoints: 5,
        required: true,
      },
      {
        id: "q4",
        type: "matrix",
        question: "Please rate the following aspects of the training materials:",
        rowLabels: ["Slides / presentations", "Handouts / guides", "Interactive tools", "Reference materials"],
        colLabels: ["Poor", "Fair", "Good", "Very Good", "Excellent"],
        matrixType: "radio",
        required: true,
      },
      {
        id: "q5",
        type: "yes_no",
        question: "Would you recommend this training to a colleague with similar needs?",
        displayStyle: "buttons",
        yesLabel: "Yes, definitely",
        noLabel: "Not really",
        required: true,
      },
      {
        id: "q6",
        type: "opinion_scale",
        question: "How did the training format work for you?",
        ratingScale: 7,
        leftLabel: "Not well at all",
        rightLabel: "Extremely well",
        showNumbers: true,
        required: false,
      },
      {
        id: "q7",
        type: "multiple_choice",
        question: "The length of the training was:",
        options: ["Much too short", "A bit too short", "Just right", "A bit too long", "Much too long"],
        displayStyle: "cards",
        required: false,
      },
      {
        id: "q8",
        type: "rating",
        question: "The training felt relevant to my day-to-day work.",
        ratingScale: 5,
        ratingStyle: "star",
        ratingLabels: { low: "Not relevant", high: "Very relevant" },
        required: false,
      },
      {
        id: "q9",
        type: "textarea",
        question: "What worked particularly well in this training?",
        placeholder: "Share what you found most effective...",
        rows: 4,
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "What is one thing that should definitely be improved for future sessions?",
        placeholder: "Your feedback helps us improve...",
        rows: 4,
        required: false,
      },
      {
        id: "q11",
        type: "ranking",
        question: "Rank the following topics by how much you'd like to see them explored in future training:",
        options: ["Advanced techniques", "Real-world case studies", "Hands-on practice", "Q&A with experts", "Peer discussions"],
        displayStyle: "drag",
        required: false,
      },
    ],
  },
  {
    id: "behaviour_change_followup",
    title: "Behaviour Change & Application (2–6 Weeks)",
    description: "Checks whether participants are applying what they learned on the job and what's helping or blocking them (Level 3: Behaviour).",
    timing: "2–6 weeks after training",
    audience: "Participants",
    topic: "application",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How often have you applied what you learned in this training to your work in the past 2–6 weeks?",
        options: ["Daily", "Several times per week", "About once per week", "Rarely", "Not at all"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "To what extent has this training changed how you approach your work?",
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which of the following outcomes have you experienced as a result of applying this training?",
        options: ["I save time", "I make fewer errors", "The quality of my work has improved", "Collaboration with others has improved", "I feel more confident", "No noticeable change yet"],
        required: false,
      },
      {
        id: "q4",
        type: "textarea",
        question: "What has helped you most in applying what you learned?",
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What has made it difficult to apply what you learned?",
        required: false,
      },
      {
        id: "q6",
        type: "rating",
        question: "Compared to before the training, how confident do you feel now in this skill area?",
        required: true,
      },
      {
        id: "q7",
        type: "multiple_choice",
        question: "Have you shared what you learned with colleagues (e.g., explaining concepts, showing tools, coaching others)?",
        options: ["Yes, in a formal way (presentations, demos, etc.)", "Yes, informally in conversations", "Not yet"],
        required: false,
      },
      {
        id: "q8",
        type: "textarea",
        question: "Have you noticed any feedback from others (manager, peers, customers) about changes in your behaviour after the training?",
        required: false,
      },
      {
        id: "q9",
        type: "textarea",
        question: "What is one behaviour change from this training that you want to make more consistent?",
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "What additional support (coaching, refreshers, tools) would help you maintain or deepen these behaviour changes?",
        required: false,
      },
    ],
  },
  {
    id: "manager_observation_followup",
    title: "Manager Observation Follow-Up",
    description: "Asks managers whether they observe behavioural changes and impact in their direct reports after training.",
    timing: "2–6 weeks after training",
    audience: "Managers",
    topic: "manager",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In the past 2–6 weeks, how often have you observed your team member applying skills or behaviours from this training?",
        options: ["Frequently", "Sometimes", "Rarely", "I have not observed this"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "To what extent has this training improved your team member's performance in their role?",
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which areas have you noticed improvements in? (Select all that apply.)",
        options: ["Quality of work", "Speed / efficiency", "Ownership and initiative", "Collaboration with others", "Communication", "Customer / stakeholder outcomes"],
        required: false,
      },
      {
        id: "q4",
        type: "rating",
        question: "How supportive is your environment (systems, processes, culture) in enabling this person to apply what they learned?",
        required: true,
      },
      {
        id: "q5",
        type: "multiple_choice",
        question: "Since the training, have you adjusted this person's goals, responsibilities, or expectations to reflect new skills?",
        options: ["Yes, formal changes (goals, KPIs, responsibilities)", "Yes, informal adjustments", "No changes"],
        required: false,
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "Have you provided specific feedback or coaching related to the training content?",
        options: ["Yes, on a regular basis", "Yes, once or twice", "No"],
        required: false,
      },
      {
        id: "q7",
        type: "textarea",
        question: "Please describe one example where you observed this person positively applying something from the training.",
        required: false,
      },
      {
        id: "q8",
        type: "textarea",
        question: "Are there any areas where you expected to see more change or improvement than you have so far?",
        required: false,
      },
      {
        id: "q9",
        type: "textarea",
        question: "What additional support or resources from the organization would help this person sustain their new skills or behaviours?",
        required: false,
      },
      {
        id: "q10",
        type: "rating",
        question: "Overall, how valuable do you feel this training has been for this person's performance and development?",
        required: false,
      },
    ],
  },
  {
    id: "training_transfer_barriers_support",
    title: "Training Transfer: Barriers & Support Needs",
    description: "Explores environmental and organisational factors that help or hinder applying training on the job.",
    timing: "2–6 weeks after training",
    audience: "Participants",
    topic: "application",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "How easy or difficult is it to apply what you learned in your actual work environment?",
        required: true,
      },
      {
        id: "q2",
        type: "checkbox",
        question: "Which factors most support you in applying this training?",
        options: ["Support from my manager", "Support from colleagues / team", "Clear processes and expectations", "Tools and systems that make it easier", "Time and space to practice new skills"],
        required: false,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which factors most make it difficult to apply this training?",
        options: ["Time pressure / workload", "Existing habits or ways of working", "Lack of support from manager or team", "Processes or policies that conflict with new behaviours", "Unclear expectations from leadership"],
        required: false,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "Have you received any follow-up support (coaching, check-ins, refreshers) related to this training?",
        options: ["Yes, regular follow-up", "Yes, once or twice", "No follow-up"],
        required: true,
      },
      {
        id: "q5",
        type: "rating",
        question: "Do you feel your manager actively encourages you to use what you learned in this training?",
        required: false,
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "Do your current goals or KPIs reflect the behaviours or skills covered in the training?",
        options: ["Yes, clearly", "Somewhat", "No", "Not sure"],
        required: false,
      },
      {
        id: "q7",
        type: "textarea",
        question: "Have you encountered any conflicting instructions (e.g., asked to work in ways that go against what was taught)?",
        required: false,
      },
      {
        id: "q8",
        type: "textarea",
        question: "What specific changes in tools, processes, or policies would make it easier to apply this training?",
        required: false,
      },
      {
        id: "q9",
        type: "rating",
        question: "How likely are you to continue using what you learned over the next 3–6 months?",
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "What type of support would most help you use this training more consistently?",
        required: false,
      },
    ],
  },
  {
    id: "training_roi_impact",
    title: "Training ROI & Impact (Self + Manager)",
    description: "Captures perceived business impact of the training, including productivity, quality, and confidence (Level 4: Results).",
    timing: "Weeks or months after training",
    audience: "Participants & Managers",
    topic: "roi",
    questionCount: 10,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "Since completing this training, how has your overall productivity changed in the areas related to the training?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "To what extent has this training reduced errors, rework, or issues in your work?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "To what extent has this training improved outcomes for your internal or external customers?",
        required: true,
      },
      {
        id: "q4",
        type: "number",
        question: "If you had to estimate, how many hours per month do you save (or could you save) because of what you learned in this training?",
        required: false,
      },
      {
        id: "q5",
        type: "rating",
        question: "How likely are you to recommend continued or expanded investment in this training for others in your organization?",
        required: true,
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "Has this training contributed to achieving any key team or organizational goals (e.g., revenue, quality, safety, customer satisfaction)?",
        options: ["Yes, clearly", "Yes, somewhat", "No", "Not sure"],
        required: false,
      },
      {
        id: "q7",
        type: "textarea",
        question: "If applicable, briefly describe any measurable results (metrics, KPIs, targets) that you believe have improved due to this training.",
        required: false,
      },
      {
        id: "q8",
        type: "rating",
        question: "From a cost–benefit perspective, how would you rate the value of this training to the organization?",
        required: false,
      },
      {
        id: "q9",
        type: "textarea",
        question: "In your own words, what tangible impact has this training had on your work or your team?",
        required: false,
      },
      {
        id: "q10",
        type: "textarea",
        question: "What would make this training even more valuable or impactful?",
        required: false,
      },
    ],
  },
  {
    id: "canada-engagement-wellbeing-v1",
    title: "Canada Employee Engagement & Wellbeing Index",
    description: "A comprehensive engagement and wellbeing survey designed for Canadian organizations, focusing on trust, inclusion, psychological safety, and sustainable performance.",
    timing: "Quarterly",
    audience: "Employees",
    topic: "assessment",
    questionCount: 31,
    scoreConfig: {
      enabled: true,
      categories: [
        { id: "engagement_core", name: "Engagement" },
        { id: "enablement", name: "Enablement & Resources" },
        { id: "leadership_trust", name: "Leadership & Trust" },
        { id: "inclusion", name: "Inclusion, Respect & Equity" },
        { id: "wellbeing", name: "Wellbeing & Psychological Safety" },
        { id: "growth", name: "Growth & Development" },
        { id: "culture", name: "Culture & Values" },
      ],
      scoreRanges: [
        {
          id: "at-risk",
          min: 0,
          max: 49,
          label: "At Risk",
          color: "#B91C1C",
          shortDescription: "Serious risks to engagement and wellbeing",
          longDescription: "Scores in this range indicate systemic issues impacting engagement, wellbeing, or inclusion. Immediate, focused action planning is recommended.",
        },
        {
          id: "vulnerable",
          min: 50,
          max: 64,
          label: "Vulnerable",
          color: "#F97316",
          shortDescription: "Vulnerable",
          longDescription: "Employees experience mixed signals. Some strengths exist, but key friction points are likely affecting retention and performance.",
        },
        {
          id: "developing",
          min: 65,
          max: 79,
          label: "Developing",
          color: "#EAB308",
          shortDescription: "Developing",
          longDescription: "Foundations of engagement are present, but consistency is lacking. Targeted improvements can move the organization into “Healthy” territory.",
        },
        {
          id: "healthy",
          min: 80,
          max: 100,
          label: "Healthy",
          color: "#16A34A",
          shortDescription: "Healthy",
          longDescription: "Employees generally feel engaged, supported, and included. Focus on sustaining strengths and addressing localized hot spots.",
        },
      ],
      resultsScreen: {
        enabled: true,
        layout: "dashboard",
        showTotalScore: true,
        showPercentage: true,
        showOverallBand: true,
        showCategoryBreakdown: true,
        showCategoryBands: true,
        showStrengthsAndRisks: true,
        showCallToAction: true,
        title: "Your Engagement & Wellbeing Snapshot",
        subtitle: "See how your organization scores across engagement, enablement, leadership, inclusion, wellbeing, and growth.",
        footerNote: "Results are confidential and should be interpreted in context with qualitative feedback and organizational priorities.",
        ctaLabel: "Download action planning guide",
        ctaUrl: "https://example.com/action-planning-guide",
        themeVariant: "teal",
        scoreRanges: [
          { id: "at-risk", min: 0, max: 49, label: "At Risk", color: "#B91C1C" },
          { id: "vulnerable", min: 50, max: 64, label: "Vulnerable", color: "#F97316" },
          { id: "developing", min: 65, max: 79, label: "Developing", color: "#EAB308" },
          { id: "healthy", min: 80, max: 100, label: "Healthy", color: "#16A34A" },
        ],
        categories: [
          { categoryId: "engagement_core", show: true, emphasize: true, bandsMode: "inherit" },
          { categoryId: "enablement", show: true, bandsMode: "inherit" },
          { categoryId: "leadership_trust", show: true, bandsMode: "inherit" },
          { categoryId: "inclusion", show: true, bandsMode: "inherit" },
          { categoryId: "wellbeing", show: true, bandsMode: "inherit" },
          { categoryId: "growth", show: true, bandsMode: "inherit" },
          { categoryId: "culture", show: true, bandsMode: "inherit" },
        ],
      },
    },
    questions: [
      { id: "q1", type: "rating", question: "I am proud to work for this organization.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.5, scoringCategory: "engagement_core" },
      { id: "q2", type: "rating", question: "I would recommend this organization as a great place to work.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.5, scoringCategory: "engagement_core" },
      { id: "q3", type: "rating", question: "Most days, I look forward to going to work.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "engagement_core" },
      { id: "q4", type: "rating", question: "I see myself still working here two years from now.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "engagement_core" },
      { id: "q5", type: "rating", question: "I have the tools, technology, and resources I need to do my job well.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "enablement" },
      { id: "q6", type: "rating", question: "My workload is reasonable enough for me to do quality work.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "enablement" },
      { id: "q7", type: "rating", question: "I can access support when I’m facing operational or client-related challenges.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "enablement" },
      { id: "q8", type: "rating", question: "I have sufficient flexibility in how, when, or where I work to manage personal responsibilities.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "enablement" },
      { id: "q9", type: "rating", question: "I trust senior leadership to make decisions that are in the best interests of employees and clients.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "leadership_trust" },
      { id: "q10", type: "rating", question: "My immediate manager communicates clearly and transparently about changes that affect my work.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "leadership_trust" },
      { id: "q11", type: "rating", question: "I feel comfortable raising concerns or ideas with my manager.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "leadership_trust" },
      { id: "q12", type: "rating", question: "Leaders in this organization role-model the values they promote.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "leadership_trust" },
      { id: "q13", type: "rating", question: "I feel respected by my coworkers.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "inclusion" },
      { id: "q14", type: "rating", question: "People from diverse backgrounds are treated fairly and equitably here.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "inclusion" },
      { id: "q15", type: "rating", question: "I feel comfortable being myself at work without fear of negative consequences.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "inclusion" },
      { id: "q16", type: "rating", question: "I believe this organization actively works to prevent harassment and discrimination.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "inclusion" },
      { id: "q17", type: "rating", question: "I feel psychologically safe to speak up about mistakes, risks, or concerns.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.3, scoringCategory: "wellbeing" },
      { id: "q18", type: "rating", question: "My work rarely has a negative impact on my mental health.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.3, scoringCategory: "wellbeing" },
      { id: "q19", type: "rating", question: "This organization provides meaningful support for employee wellbeing and mental health.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.1, scoringCategory: "wellbeing" },
      { id: "q20", type: "rating", question: "I can disconnect from work (email, messages, calls) outside of my normal working hours.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "wellbeing" },
      { id: "q21", type: "rating", question: "I have good opportunities to learn and grow in this organization.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.1, scoringCategory: "growth" },
      { id: "q22", type: "rating", question: "I receive useful feedback that helps me improve my performance.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "growth" },
      { id: "q23", type: "rating", question: "I can see a clear path for my career development here.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.1, scoringCategory: "growth" },
      { id: "q24", type: "rating", question: "The everyday behaviours I see at work are aligned with our stated values.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "culture" },
      { id: "q25", type: "rating", question: "Different teams and departments collaborate effectively to serve clients and communities.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "culture" },
      { id: "q26", type: "rating", question: "I understand how my work contributes to the organization’s mission and priorities.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "culture" },
      { id: "q27", type: "textarea", question: "What is one thing this organization is doing well that we should protect or build on?", required: false, scorable: false },
      { id: "q28", type: "textarea", question: "What is one change that would most improve your experience at work?", required: false, scorable: false },
      { id: "q29", type: "textarea", question: "Is there anything else you would like to share about your experience working here in Canada?", required: false, scorable: false },
      {
        id: "q30",
        type: "multiple_choice",
        question: "Which region do you primarily work in?",
        options: ["British Columbia", "Prairies (AB, SK, MB)", "Ontario", "Québec", "Atlantic Canada", "Northern Territories", "Outside Canada"],
        required: false,
        scorable: false,
      },
      {
        id: "q31",
        type: "multiple_choice",
        question: "How long have you worked with this organization?",
        options: ["Less than 6 months", "6–12 months", "1–3 years", "3–5 years", "5–10 years", "More than 10 years"],
        required: false,
        scorable: false,
      },
    ],
  },
  {
    id: "canada-engagement-pulse-v1",
    title: "Canada Employee Engagement Pulse",
    description: "A lightweight pulse survey to quickly track engagement, trust, inclusion, and wellbeing across Canadian organizations.",
    timing: "Monthly",
    audience: "Employees",
    topic: "assessment",
    questionCount: 7,
    scoreConfig: {
      enabled: true,
      categories: [
        { id: "engagement_core", name: "Engagement" },
        { id: "leadership_trust", name: "Leadership & Trust" },
        { id: "inclusion", name: "Inclusion & Respect" },
        { id: "wellbeing", name: "Wellbeing" },
      ],
      scoreRanges: [
        { id: "at-risk", min: 0, max: 49, label: "At Risk", color: "#B91C1C" },
        { id: "vulnerable", min: 50, max: 64, label: "Vulnerable", color: "#F97316" },
        { id: "developing", min: 65, max: 79, label: "Developing", color: "#EAB308" },
        { id: "healthy", min: 80, max: 100, label: "Healthy", color: "#16A34A" },
      ],
      resultsScreen: {
        enabled: true,
        layout: "simple",
        showTotalScore: true,
        showPercentage: true,
        showOverallBand: true,
        showCategoryBreakdown: true,
        showCategoryBands: false,
        showStrengthsAndRisks: false,
        showCallToAction: false,
        title: "Engagement Pulse Snapshot",
        subtitle: "A quick view of how your people are feeling right now.",
        themeVariant: "teal",
      },
    },
    questions: [
      { id: "p1", type: "rating", question: "I would recommend this organization as a great place to work.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.5, scoringCategory: "engagement_core" },
      { id: "p2", type: "rating", question: "Most days, I feel motivated to do my best work here.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "engagement_core" },
      { id: "p3", type: "rating", question: "I trust my manager to support me when I raise a concern.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "leadership_trust" },
      { id: "p4", type: "rating", question: "I feel respected by the people I work with.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1.2, scoringCategory: "inclusion" },
      { id: "p5", type: "rating", question: "My workload feels sustainable over the next few months.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "wellbeing" },
      { id: "p6", type: "rating", question: "I can disconnect from work outside of my normal working hours.", ratingScale: 5, required: true, scorable: true, scoreWeight: 1, scoringCategory: "wellbeing" },
      { id: "p7", type: "textarea", question: "In a sentence or two, how are you feeling about work right now?", required: false, scorable: false },
    ],
  },
];

// Scoring helpers for assessment-style templates
const defaultAssessmentScoreConfig: SurveyScoreConfig = {
  enabled: true,
  categories: [{ id: "overall", name: "Overall" }],
  scoreRanges: [
    { id: "low", min: 0, max: 40, label: "Low" },
    { id: "medium", min: 41, max: 70, label: "Medium" },
    { id: "high", min: 71, max: 100, label: "High" },
  ],
  resultsScreen: {
    enabled: true,
    layout: "bands" as const,
    showTotalScore: true,
    showPercentage: true,
    showOverallBand: true,
    showCategoryBreakdown: true,
    showCategoryBands: true,
    showStrengthsAndRisks: true,
    showCallToAction: true,
    ctaLabel: "Share summary with your manager",
    ctaUrl: "https://example.com/share",
    scoreRanges: [
      { id: "low", min: 0, max: 40, label: "At risk" },
      { id: "medium", min: 41, max: 70, label: "Mixed" },
      { id: "high", min: 71, max: 100, label: "Healthy" },
    ],
    categories: [{ categoryId: "overall", show: true, emphasize: true, bandsMode: "inherit" }],
  },
};

function buildOptionScores(options?: string[] | null): Record<string, number> | undefined {
  if (!options || options.length === 0) return undefined;
  const maxScore = options.length;
  return options.reduce<Record<string, number>>((acc, option, idx) => {
    acc[option] = maxScore - idx;
    return acc;
  }, {});
}

function applyAssessmentScoring(template: SurveyTemplate): SurveyTemplate {
  if (template.topic !== "assessment") {
    return {
      ...template,
      questions: normalizeQuestions(template.questions),
    };
  }

  const scoredQuestions = template.questions.map<Question>((q) => {
    const optionScores = buildOptionScores(q.options);
    return {
      ...q,
      scorable: true,
      scoringCategory: "overall",
      scoreWeight: q.scoreWeight ?? 1,
      optionScores: q.optionScores || optionScores,
    };
  });

  return {
    ...template,
    scoreConfig: template.scoreConfig || defaultAssessmentScoreConfig,
    questions: normalizeQuestions(scoredQuestions),
  };
}

// Export templates with scoring applied where appropriate
export const surveyTemplates: SurveyTemplate[] = baseTemplates.map(applyAssessmentScoring);

export const templateCategories = [
  { id: "assessment", label: "Assessment", description: "Identify needs and readiness" },
  { id: "feedback", label: "Feedback", description: "Gather real-time reactions" },
  { id: "knowledge", label: "Knowledge", description: "Measure understanding" },
  { id: "satisfaction", label: "Satisfaction", description: "Evaluate experience" },
  { id: "application", label: "Application", description: "Track on-the-job use" },
  { id: "manager", label: "Manager Feedback", description: "Leadership observations" },
  { id: "roi", label: "ROI & Impact", description: "Business outcomes" },
];

export function getTemplatesByCategory(category: string): SurveyTemplate[] {
  return surveyTemplates.filter((t) => t.topic === category);
}
