import type { Question } from "@/components/QuestionCard";

export interface SurveyTemplate {
  id: string;
  title: string;
  description: string;
  timing: string;
  audience: string;
  topic: "assessment" | "feedback" | "knowledge" | "satisfaction" | "application" | "manager" | "roi";
  questionCount: number;
  questions: Question[];
}

export const surveyTemplates: SurveyTemplate[] = [
  {
    id: "pre_training_needs_assessment",
    title: "Pre-Training Needs Assessment",
    description: "Identifies current skill level, pain points, and expectations before training.",
    timing: "Before training",
    audience: "Participants",
    topic: "assessment",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "Which best describes your current role?",
        options: ["Individual contributor", "People manager", "Senior leader / executive", "Other"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How familiar are you with the topic of this training?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "How confident do you currently feel performing tasks related to this topic in your day-to-day work?",
        required: true,
      },
      {
        id: "q4",
        type: "checkbox",
        question: "Which areas do you struggle with most related to this topic?",
        options: [
          "I don't know what to do",
          "I know what to do but find it hard to do",
          "Time pressure / workload",
          "Tools, systems, or processes",
          "Lack of support or alignment from others",
          "Other",
        ],
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What would make this training most valuable for you personally?",
        required: false,
      },
      {
        id: "q6",
        type: "rating",
        question: "How urgent is it for you to improve your skills in this area?",
        required: true,
      },
    ],
  },
  {
    id: "pre_training_readiness_motivation",
    title: "Pre-Training Readiness & Motivation",
    description: "Assesses learner motivation, mindset, and potential barriers before training starts.",
    timing: "Before training",
    audience: "Participants",
    topic: "assessment",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "How motivated are you to actively participate in this training?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How relevant do you believe this training is to your current role and responsibilities?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "How much support do you feel you have from your manager to apply what you learn in this training?",
        required: true,
      },
      {
        id: "q4",
        type: "checkbox",
        question: "What might prevent you from fully engaging with this training?",
        options: [
          "Competing priorities / time conflicts",
          "Unclear relevance to my role",
          "Technology or access issues",
          "High workload during the training period",
          "Personal factors (energy, focus, etc.)",
          "Other",
        ],
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "In one sentence, what would 'success' from this training look like for you?",
        required: false,
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "Do you understand the objectives and structure of this training?",
        options: ["Yes, very clear", "Somewhat clear", "Not clear at all"],
        required: true,
      },
    ],
  },
  {
    id: "mid_training_pulse_check",
    title: "Mid-Training Pulse Check",
    description: "Brief check-in during training to adjust pacing, format, and support.",
    timing: "During training",
    audience: "Participants",
    topic: "feedback",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How would you rate the pace of the training so far?",
        options: ["Too slow", "About right", "Too fast"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How confident do you feel in your understanding of the material covered so far?",
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which training components are most helpful for your learning?",
        options: [
          "Presentations / lectures",
          "Group discussions",
          "Hands-on activities / practice",
          "Case studies / scenarios",
          "Slides, handouts, or reference materials",
        ],
        required: false,
      },
      {
        id: "q4",
        type: "rating",
        question: "How engaged do you feel during the sessions so far?",
        required: true,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What is one thing the trainer could change right now to improve your learning experience?",
        required: false,
      },
      {
        id: "q6",
        type: "multiple_choice",
        question: "Do you feel comfortable asking questions or speaking up during the training?",
        options: ["Yes, often", "Sometimes", "Rarely", "No"],
        required: true,
      },
    ],
  },
  {
    id: "session_level_feedback",
    title: "Session-Level Feedback",
    description: "Captures feedback on a specific training session, module, or class.",
    timing: "Immediately after session",
    audience: "Participants",
    topic: "feedback",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "Overall, how would you rate this session?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "The objectives of the session were clear.",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "The trainer was well-prepared and organized.",
        required: true,
      },
      {
        id: "q4",
        type: "rating",
        question: "The content level (difficulty, depth) was appropriate for me.",
        required: true,
      },
      {
        id: "q5",
        type: "textarea",
        question: "Which part(s) of this session did you find most valuable?",
        required: false,
      },
      {
        id: "q6",
        type: "textarea",
        question: "What, if anything, should be changed or improved in this session?",
        required: false,
      },
    ],
  },
  {
    id: "post_training_knowledge_check",
    title: "Post-Training Knowledge Check",
    description: "Assesses knowledge and understanding immediately after training.",
    timing: "Immediately after training",
    audience: "Participants",
    topic: "knowledge",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "How confident are you that you can explain the key concepts covered in this training to a colleague?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "How well do you understand when and where to apply what you learned?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "If you were given a real work scenario related to this topic, how confident are you that you could handle it using what you learned?",
        required: true,
      },
      {
        id: "q4",
        type: "textarea",
        question: "List one specific concept, tool, or technique from this training that you feel you understand very well.",
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "List one concept, tool, or technique that you would like more practice or clarification on.",
        required: false,
      },
      {
        id: "q6",
        type: "rating",
        question: "How likely are you to use what you learned in the next 2 weeks?",
        required: true,
      },
    ],
  },
  {
    id: "post_training_satisfaction_experience",
    title: "Post-Training Satisfaction & Experience",
    description: "Measures reactions to the overall training experience (classic Level 1).",
    timing: "Immediately after training",
    audience: "Participants",
    topic: "satisfaction",
    questionCount: 7,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "Overall, how satisfied are you with this training?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "The training met my expectations.",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "The trainer created an inclusive and respectful learning environment.",
        required: true,
      },
      {
        id: "q4",
        type: "rating",
        question: "The training materials (slides, handouts, tools) supported my learning effectively.",
        required: true,
      },
      {
        id: "q5",
        type: "multiple_choice",
        question: "Would you recommend this training to a colleague with similar needs?",
        options: ["Yes", "No", "Not sure"],
        required: true,
      },
      {
        id: "q6",
        type: "textarea",
        question: "What worked particularly well in this training?",
        required: false,
      },
      {
        id: "q7",
        type: "textarea",
        question: "What is one thing that should definitely be improved for future sessions?",
        required: false,
      },
    ],
  },
  {
    id: "behaviour_change_followup",
    title: "Behaviour Change & Application (2–6 Weeks)",
    description: "Checks whether participants are applying what they learned on the job and what's helping or blocking them.",
    timing: "2–6 weeks after training",
    audience: "Participants",
    topic: "application",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "How often have you applied what you learned in this training to your work in the past 2–6 weeks?",
        options: ["Daily", "Several times per week", "About once per week", "Rarely", "Not at all"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "To what extent has this training changed how you approach your work?",
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which of the following outcomes have you experienced as a result of applying this training?",
        options: [
          "I save time",
          "I make fewer errors",
          "The quality of my work has improved",
          "Collaboration with others has improved",
          "I feel more confident",
          "No noticeable change yet",
        ],
        required: false,
      },
      {
        id: "q4",
        type: "textarea",
        question: "What has helped you most in applying what you learned?",
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What has made it difficult to apply what you learned?",
        required: false,
      },
      {
        id: "q6",
        type: "rating",
        question: "Compared to before the training, how confident do you feel now in this skill area?",
        required: true,
      },
    ],
  },
  {
    id: "manager_observation_followup",
    title: "Manager Observation Follow-Up",
    description: "Asks managers whether they observe behavioural changes and impact in their direct reports after training.",
    timing: "2–6 weeks after training",
    audience: "Managers",
    topic: "manager",
    questionCount: 5,
    questions: [
      {
        id: "q1",
        type: "multiple_choice",
        question: "In the past 2–6 weeks, how often have you observed your team member applying skills or behaviours from this training?",
        options: ["Frequently", "Sometimes", "Rarely", "I have not observed this"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "To what extent has this training improved your team member's performance in their role?",
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which areas have you noticed improvements in? (Select all that apply.)",
        options: [
          "Quality of work",
          "Speed / efficiency",
          "Ownership and initiative",
          "Collaboration with others",
          "Communication",
          "Customer / stakeholder outcomes",
        ],
        required: false,
      },
      {
        id: "q4",
        type: "rating",
        question: "How supportive is your environment (systems, processes, culture) in enabling this person to apply what they learned?",
        required: true,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What additional support or follow-up would help your team member sustain or deepen these improvements?",
        required: false,
      },
    ],
  },
  {
    id: "training_transfer_barriers_support",
    title: "Training Transfer: Barriers & Support Needs",
    description: "Explores environmental and organisational factors that help or hinder applying training on the job.",
    timing: "2–6 weeks after training",
    audience: "Participants",
    topic: "application",
    questionCount: 5,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "How easy or difficult is it to apply what you learned in your actual work environment?",
        required: true,
      },
      {
        id: "q2",
        type: "checkbox",
        question: "Which factors most support you in applying this training?",
        options: [
          "Support from my manager",
          "Support from colleagues / team",
          "Clear processes and expectations",
          "Tools and systems that make it easier",
          "Time and space to practice new skills",
        ],
        required: false,
      },
      {
        id: "q3",
        type: "checkbox",
        question: "Which factors most make it difficult to apply this training?",
        options: [
          "Time pressure / workload",
          "Existing habits or ways of working",
          "Lack of support from manager or team",
          "Processes or policies that conflict with new behaviours",
          "Unclear expectations from leadership",
        ],
        required: false,
      },
      {
        id: "q4",
        type: "multiple_choice",
        question: "Have you received any follow-up support (coaching, check-ins, refreshers) related to this training?",
        options: ["Yes, regular follow-up", "Yes, once or twice", "No follow-up"],
        required: true,
      },
      {
        id: "q5",
        type: "textarea",
        question: "What type of support would most help you use this training more consistently?",
        required: false,
      },
    ],
  },
  {
    id: "training_roi_impact",
    title: "Training ROI & Impact (Self + Manager)",
    description: "Captures perceived business impact of the training, including productivity, quality, and confidence.",
    timing: "Weeks or months after training",
    audience: "Participants & Managers",
    topic: "roi",
    questionCount: 6,
    questions: [
      {
        id: "q1",
        type: "rating",
        question: "Since completing this training, how has your overall productivity changed in the areas related to the training?",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        question: "To what extent has this training reduced errors, rework, or issues in your work?",
        required: true,
      },
      {
        id: "q3",
        type: "rating",
        question: "To what extent has this training improved outcomes for your internal or external customers?",
        required: true,
      },
      {
        id: "q4",
        type: "number",
        question: "If you had to estimate, how many hours per month do you save (or could you save) because of what you learned in this training?",
        required: false,
      },
      {
        id: "q5",
        type: "rating",
        question: "How likely are you to recommend continued or expanded investment in this training for others in your organization?",
        required: true,
      },
      {
        id: "q6",
        type: "textarea",
        question: "In your own words, what tangible impact has this training had on your work or your team?",
        required: false,
      },
    ],
  },
];

// Template categories for organizing/sorting
export const templateCategories = [
  { id: "assessment", label: "Assessment", description: "Identify needs and readiness" },
  { id: "feedback", label: "Feedback", description: "Gather real-time reactions" },
  { id: "knowledge", label: "Knowledge", description: "Measure understanding" },
  { id: "satisfaction", label: "Satisfaction", description: "Evaluate experience" },
  { id: "application", label: "Application", description: "Track on-the-job use" },
  { id: "manager", label: "Manager Feedback", description: "Leadership observations" },
  { id: "roi", label: "ROI & Impact", description: "Business outcomes" },
];

// Get templates grouped by category
export function getTemplatesByCategory(category: string): SurveyTemplate[] {
  return surveyTemplates.filter((t) => t.topic === category);
}
